CREATE TABLE IF NOT EXISTS recus_paiements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_recu VARCHAR(20) NOT NULL,
    type_document ENUM('ticket', 'bordereau') NOT NULL,
    id_document INT NOT NULL,
    numero_document VARCHAR(50) NOT NULL,
    montant_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    montant_paye DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    montant_precedent DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    reste_a_payer DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    id_agent INT,
    nom_agent VARCHAR(100),
    contact_agent VARCHAR(20),
    nom_usine VARCHAR(100),
    matricule_vehicule VARCHAR(20),
    id_caissier INT NOT NULL,
    nom_caissier VARCHAR(100) NOT NULL,
    source_paiement ENUM('transactions', 'financement') NOT NULL,
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_numero_recu (numero_recu),
    INDEX idx_type_document (type_document),
    INDEX idx_id_document (id_document),
    INDEX idx_id_agent (id_agent),
    INDEX idx_id_caissier (id_caissier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
